# Generated by Django 6.0 on 2025-12-30 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publishers/', verbose_name='لوگوی ناشر')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام ناشر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشران',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='اسلاگ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=255, verbose_name='نام کتاب')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('author', models.CharField(max_length=255, verbose_name='نویسنده')),
                ('main_topic', models.CharField(max_length=150, verbose_name='موضوع اصلی')),
                ('secondary_topic', models.CharField(blank=True, max_length=150, verbose_name='موضوع فرعی')),
                ('translator', models.CharField(blank=True, max_length=255, verbose_name='مترجم')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('language', models.CharField(max_length=50, verbose_name='زبان')),
                ('more', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.publisher', verbose_name='ناشر')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-created'],
            },
        ),
    ]
