# Generated by Django 6.0.4 on 2026-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='translator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مترجم'),
        ),
    ]
